### ISSUE TITLE
想请教您一下关于测试时采样部分的代码

### ISSUE THREAD

**Issue by YouXMu** [htyjers/StrDiffusion#41]
![image](https://github.com/user-attachments/assets/113317da-2a11-4f4d-b966-153d6d44c84c)

您好，我在查看您在论文里提到的自适应采样部分的代码时，发现您又对xs（结构分支进行去噪时的起始状态）进行了更新，也就是一开始的两行代码。我的疑惑点在于：
🔺xs 一开始不就代表着结构分支去噪时的起始状态吗？为什么还要更新呢？与不更新xs，直接进行S_sde.score_fn（）以及S_sde.reverse_sde_step（）有什么区别呢？

**Comment by htyjers** [comment]
Thank you for your attention: 
1. In image inpainting, the unmasked regions are known, so I provide the unmasked region before denoising to achieve better results.
2. The Adaptive Resampling Strategy requires several iterations of adding and removing noise, so fixing the unmasked regions can help reduce the instability caused by the random noise addition.

**Comment by YouXMu** [comment]
感谢您的耐心回复，现在我理解了这样做的原因了，祝您生活愉快！
